image: node

stages:
  - npm_dependencies
  - test

npm_dependencies:
  stage: npm_dependencies
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - npm_dependencies
  script:
    - npm test
